-- HR Cache Database Export
-- Generated at: 2026-04-22T20:54:02.314Z

PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS knowledge_base;
CREATE TABLE knowledge_base (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    question_original TEXT NOT NULL,
                    question_normalized TEXT NOT NULL,
                    answer TEXT NOT NULL,
                    category TEXT DEFAULT 'general',
                    usage_count INTEGER DEFAULT 1,
                    last_used DATETIME DEFAULT CURRENT_TIMESTAMP,
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
                , source TEXT DEFAULT 'notebooklm', knowledge_version INTEGER DEFAULT 0, last_validated DATETIME DEFAULT NULL);

INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (1, 'HOLA, QUISIERA SABER CUAL ES MI TURNO LA PROXIMA SEMANA', 'hola quisiera saber cual es mi turno la proxima semana', 'El Reglamento Interno de Trabajo no especifica los turnos individuales, ya que la programación, distribución y rotación de estos se determina mediante disposición interna y debe ser comunicada oportunamente a cada trabajador [1]. Para conocer tu turno exacto de la próxima semana, por favor consulta directamente con tu jefe inmediato o con Recursos Humanos.', 'general', 1, '2026-03-04 17:25:23', '2026-03-04 17:25:23', 'notebooklm', 0, '2026-03-04 17:25:23');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (2, 'Periodo de prueba', 'periodo de prueba', '```json
{
  "classification": "reglamento",
  "answer": "El periodo de prueba en PLASTITEC busca evaluar las aptitudes del trabajador y las condiciones laborales, debiendo acordarse siempre por escrito [1]. Este periodo tiene una duración máxima de dos (2) meses y, para contratos menores a un año, no puede superar la quinta parte del término inicialmente pactado [1]. Durante esta etapa, cualquiera de las partes puede dar por terminado el contrato sin previo aviso, garantizando siempre al trabajador el pago de todas sus prestaciones sociales [1]."
}
```', 'general', 7, '2026-04-13 20:36:12', '2026-03-04 17:26:00', 'notebooklm', 0, '2026-03-05 15:34:41');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (3, 'HLA', 'hla', '¡Hola! Soy el asistente de Recursos Humanos de PLASTITEC. ¿En qué puedo ayudarte el día de hoy con respecto al Reglamento Interno de Trabajo?', 'general', 1, '2026-03-04 17:26:25', '2026-03-04 17:26:25', 'notebooklm', 0, '2026-03-04 17:26:25');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (4, 'HOLA. QUISIERA SABER CUAL ES MI TURNO LA SIGUIENTE SEMANA', 'hola quisiera saber cual es mi turno la siguiente semana', 'La programación, distribución y rotación de los turnos se determina mediante disposición interna y se comunica oportunamente a los trabajadores [1]. El Reglamento no establece los horarios específicos para cada turno personal [1]. Por favor, consulta directamente con tu jefe inmediato o con el área encargada para conocer tu programación exacta de la siguiente semana.', 'general', 1, '2026-03-04 17:27:09', '2026-03-04 17:27:09', 'notebooklm', 0, '2026-03-04 17:27:09');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (5, 'SI MI TIO SE MUERE TENGO LICENCIA DE LUTO', 'si mi tio se muere tengo licencia de luto', 'El Reglamento Interno de Trabajo estipula que la licencia por luto de 5 días hábiles cubre familiares hasta el segundo grado de consanguinidad (padres, hijos, hermanos, abuelos y nietos) [1]. Dado que los tíos se encuentran en el tercer grado de consanguinidad, lamentablemente no se otorga esta licencia remunerada en dicho caso [1, 2].', 'general', 1, '2026-03-04 17:29:00', '2026-03-04 17:29:00', 'notebooklm', 0, '2026-03-04 17:29:00');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (6, 'USTED ES INSERVIBLE', 'usted es inservible', 'Lamento que tengas esa impresión. Mi función como asistente virtual es responder exclusivamente consultas relacionadas con el Reglamento Interno de Trabajo (RIT) de PLASTITEC.', 'general', 1, '2026-03-04 17:30:03', '2026-03-04 17:30:03', 'notebooklm', 0, '2026-03-04 17:30:03');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (7, 'QUE DEBO HACER SI ME PAGAN MAL UN DOMINGO', 'que debo hacer si me pagan mal un domingo', 'Para presentar una inconformidad sobre tu pago dominical, debes realizar un reclamo de forma verbal o por escrito [1]. Puedes dirigir este reclamo a tu Jefe o director de área, o si lo prefieres, directamente ante la Dirección de Recursos Humanos [1]. Ellos se encargarán de escucharte y resolver tu caso en justicia y equidad [1].', 'general', 1, '2026-03-04 17:30:47', '2026-03-04 17:30:47', 'notebooklm', 0, '2026-03-04 17:30:47');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (8, 'Yo soy tecnico t.i cual es mi turno', 'yo soy tecnico ti cual es mi turno', 'Como técnico de T.I., tus turnos varían según el día y la asignación. Los lunes y sábados (sin festivo) el turno es de 06:00 am a 02:00 pm [1]. De martes a viernes existen diferentes horarios: Turno 1 (06:00 am a 01:00 pm), Turno 2 (01:00 am a 09:00 pm), Turno 3 (09:00 am a 06:00 am), o turnos de Laboratorio/Apoyo de 07:00 am a 05:00 pm [1]. Por favor, confirma con tu jefatura cuál turno específico o de apoyo te fue asignado [1].', 'general', 1, '2026-03-04 17:35:06', '2026-03-04 17:35:06', 'notebooklm', 0, '2026-03-04 17:35:06');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (9, 'Soy tecnico T.I y mi turno actual es turno 3 me pagan horas extras', 'soy tecnico ti y mi turno actual es turno 3 me pagan horas extras', 'Tu turno regular (Turno 3) no genera horas extras por sí solo, ya que estas corresponden únicamente al tiempo que excede tu jornada ordinaria [1, 2]. Para que PLASTITEC te reconozca y pague horas extras, estas deben ser expresamente autorizadas por la empresa o tu jefe designado [1, 3]. Sin embargo, dado que tu turno abarca horario nocturno, sí tienes derecho a recibir el recargo del 35% sobre el valor del trabajo ordinario por las horas laboradas en la noche [1, 4].', 'general', 1, '2026-03-04 17:36:34', '2026-03-04 17:36:34', 'notebooklm', 0, '2026-03-04 17:36:34');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (10, 'QUISIERA SABER COM OPAGAN LOS FINES DE SEMANA', 'quisiera saber com opagan los fines de semana', 'El trabajo en domingos y festivos se remunera con un recargo sobre el salario ordinario, que actualmente es del 80% y aumentará al 90% a partir del 1 de julio de 2026 [1, 2]. Para los días sábados, la empresa puede acordar compensar el descanso repartiendo las horas durante la semana (hasta 2 horas adicionales diarias), lo cual no se considera trabajo suplementario ni horas extras [3].', 'general', 1, '2026-03-04 17:37:35', '2026-03-04 17:37:35', 'notebooklm', 0, '2026-03-04 17:37:35');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (11, 'QUISIERA SABER COMO PAGAN LOS FINES DE SEMANA EN LA EMPRESA SI TENGO TURNO ROTATIVO', 'quisiera saber como pagan los fines de semana en la empresa si tengo turno rotativo', 'Si trabajas domingos o festivos en tu turno rotativo, la empresa te pagará un recargo sobre tu salario ordinario en proporción a las horas laboradas [1]. Actualmente, este recargo es del 80% desde el 1 de julio de 2025 y aumentará al 90% a partir del 1 de julio de 2026 [2]. Ten en cuenta que puedes convenir con el empleador que tu día de descanso obligatorio sea el sábado o el domingo, reconociéndose dicho día con el recargo dominical si llegas a laborarlo [2].', 'general', 2, '2026-03-13 20:09:39', '2026-03-04 17:40:53', 'notebooklm', 0, '2026-03-13 20:10:01');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (12, 'Gracias, ¿cuántos días tengo acumulados?', 'gracias cuantos dias tengo acumulados', 'No puedo proporcionar información confidencial sobre salarios o datos personales. Para conocer tu información exacta, consulta directamente con RRHH.', 'general', 1, '2026-03-04 17:41:05', '2026-03-04 17:41:05', 'notebooklm', 0, '2026-03-04 17:41:05');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (13, 'Hola hola hola necesito saber mi turno', 'hola hola hola necesito saber mi turno', 'Para indicarte tu turno exacto, necesito saber tu cargo en PLASTITEC. Según el reglamento, el personal administrativo tiene horarios fijos [1, 2], los turnos operativos se comunican oportunamente mediante disposición interna [2] y los técnicos de T.I. cuentan con horarios rotativos ya definidos [3]. Por favor, indícame tu rol o consulta tu programación directamente con tu jefe inmediato [2].', 'general', 1, '2026-03-04 17:41:33', '2026-03-04 17:41:33', 'notebooklm', 0, '2026-03-04 17:41:33');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (14, 'QUISIERA SABER COMO PAGAN LOS FINES DE SEMANA EN LA EMPRESA SI TENGO TURNO ROTATIVO YA QUE SIENTO QUE ME LO ESTAN PAGANDO MAL', 'quisiera saber como pagan los fines de semana en la empresa si tengo turno rotativo ya que siento que me lo estan pagando mal', '{
  "classification": "reglamento",
  "answer": "De acuerdo con el reglamento, si por tu turno rotativo laboras en tu día de descanso obligatorio (domingo o el pactado), se te debe remunerar con un recargo proporcional a las horas trabajadas, que es del 80% desde julio de 2025 y 90% a partir de julio de 2026 [1, 2]. Como trabajador, tienes derecho a solicitar a Recursos Humanos un registro detallado de tus horas y el soporte de pago correspondiente [3]. Te sugiero acercarte directamente a nuestra oficina para revisar tu caso específico y garantizar que todo esté correcto."
}', 'general', 2, '2026-03-13 20:09:45', '2026-03-04 17:42:35', 'notebooklm', 0, '2026-03-13 20:09:45');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (15, 'SIENTO QUE EL DIA SABADO ME PAGAN MENOS QUE LOS OTROS DIAS', 'siento que el dia sabado me pagan menos que los otros dias', 'No puedo proporcionar información confidencial sobre salarios o datos personales. Para conocer tu información exacta, consulta directamente con RRHH.', 'general', 1, '2026-03-04 17:46:14', '2026-03-04 17:46:14', 'notebooklm', 0, '2026-03-04 17:46:14');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (16, 'Tipos de contratos y periodo de prueba', 'tipos de contratos y periodo de prueba', '{
  "classification": "reglamento",
  "answer": "En PLASTITEC manejamos contratos a término fijo [1], a término indefinido [2], por obra o labor determinada [3] y relaciones de aprendizaje [4]. El período de prueba, que debe pactarse por escrito, tiene un plazo máximo legal de dos (2) meses [5]. Para los contratos a término fijo inferiores a un año, este período no puede superar la quinta parte del término inicialmente acordado [5]."
}', 'general', 9, '2026-03-13 17:15:27', '2026-03-04 17:49:41', 'notebooklm', 0, '2026-03-05 15:34:35');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (17, 'horas extra nocturna', 'horas extra nocturna', 'El trabajo extra nocturno se remunera con un recargo del 75% sobre el valor del trabajo ordinario diurno [1]. Ten en cuenta que las horas extras no pueden exceder de 2 horas diarias y 12 semanales [2]. Además, para su pago, deben estar expresamente autorizadas por la empresa o quien esta designe [2].', 'general', 1, '2026-03-04 18:08:07', '2026-03-04 18:08:07', 'notebooklm', 0, '2026-03-04 18:08:07');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (18, 'Acoso laboral y sexual', 'acoso laboral y sexual', '{
  "classification": "reglamento",
  "answer": "El acoso laboral es toda conducta persistente orientada a infundir miedo o inducir la renuncia [1], mientras que el acoso sexual abarca cualquier hostigamiento de connotación sexual no consentido [2]. Puedes denunciar estas situaciones de forma verbal o escrita ante tu superior jerárquico o Recursos Humanos, garantizando absoluta confidencialidad y protección contra represalias [3-5]. Ambas conductas constituyen faltas graves que justifican la terminación del contrato de trabajo [6]."
}', 'general', 3, '2026-03-13 17:23:46', '2026-03-05 12:45:46', 'notebooklm', 0, '2026-03-13 17:23:46');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (19, 'Salarios y dotación', 'salarios y dotacion', 'El salario se paga mensualmente mediante consignación o cheque al finalizar cada mes e incluye la remuneración ordinaria, recargos y comisiones [1, 2]. Por su parte, la dotación se entrega de forma gratuita cada cuatro meses (30 de abril, 30 de agosto y 30 de diciembre) a los trabajadores que devenguen hasta dos salarios mínimos y lleven más de tres meses al servicio de la empresa [3].', 'general', 7, '2026-03-31 18:56:55', '2026-03-05 15:34:46', 'notebooklm', 0, '2026-03-09 20:43:39');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (20, 'Cuanto me deben', 'cuanto me deben', 'No puedo proporcionar información confidencial sobre salarios o datos personales. Para conocer tu información exacta, consulta directamente con RRHH.', 'general', 1, '2026-03-05 15:34:53', '2026-03-05 15:34:53', 'notebooklm', 0, '2026-03-05 15:34:53');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (21, 'cuando cumplo mi jornada laboral y hago 8 horas adicionales Cómo se deben pagar', 'cuando cumplo mi jornada laboral y hago 8 horas adicionales como se deben pagar', 'El reglamento establece que las horas extras no pueden exceder de dos (2) horas diarias y doce (12) semanales, por lo que no es permitido laborar 8 horas adicionales en un solo día [1, 2]. Para que este trabajo suplementario sea reconocido y pagado (con recargo del 25% diurno o 75% nocturno), debe estar expresamente autorizado por la empresa [1-3].', 'general', 1, '2026-03-05 15:36:03', '2026-03-05 15:36:03', 'notebooklm', 0, '2026-03-05 15:36:03');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (22, 'en Qué porcentaje equivale mi recargo nocturno Y a partir de Cuándo empiezan a pagarlo', 'en que porcentaje equivale mi recargo nocturno y a partir de cuando empiezan a pagarlo', 'El recargo nocturno equivale a un 35% sobre el valor del trabajo ordinario diurno [1, 2]. Actualmente, se considera trabajo nocturno el realizado entre las 9:00 p.m. y las 6:00 a.m. [1, 2]. No obstante, por la Ley 2466 de 2025, a partir de los seis meses de su sanción empezará a pagarse desde las 7:00 p.m. hasta las 6:00 a.m. [1, 2].', 'general', 1, '2026-03-05 15:37:22', '2026-03-05 15:37:22', 'notebooklm', 0, '2026-03-05 15:37:22');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (23, 'Qué pasa si hago llorar a un usuario o un compañero en mi jornada laboral', 'que pasa si hago llorar a un usuario o un companero en mi jornada laboral', 'Causar que un compañero o usuario llore por un mal trato incumple tu obligación de mantener el respeto, la armonía y las buenas relaciones en la empresa [1, 2]. Esta conducta puede considerarse maltrato laboral y un acto de grave indisciplina, lo que iniciaría un proceso disciplinario y podría resultar en la terminación de tu contrato con justa causa [3, 4].', 'general', 1, '2026-03-05 15:39:21', '2026-03-05 15:39:21', 'notebooklm', 0, '2026-03-05 15:39:21');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (24, 'Cuántas horas es permitidas elaborar el día domingo', 'cuantas horas es permitidas elaborar el dia domingo', 'El domingo es considerado legalmente como un día de descanso obligatorio de 24 horas [1]. Sin embargo, si trabajas bajo acuerdos de jornadas flexibles, el tiempo permitido es de mínimo 4 horas continuas y hasta un máximo de 9 horas diarias [2]. Si se requiere trabajo suplementario, las horas extras autorizadas no pueden exceder las 2 horas diarias [3].', 'general', 1, '2026-03-05 15:40:46', '2026-03-05 15:40:46', 'notebooklm', 0, '2026-03-05 15:40:46');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (25, 'lo que', 'lo que', 'Tu consulta está incompleta o no tiene sentido. Por favor, formula una pregunta clara relacionada con el Reglamento Interno de Trabajo de PLASTITEC.', 'general', 1, '2026-03-05 15:42:05', '2026-03-05 15:42:05', 'notebooklm', 0, '2026-03-05 15:42:05');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (26, 'Yo trabajé 10 horas seguidas un domingo Cómo deben pagarme esas horas', 'yo trabaje 10 horas seguidas un domingo como deben pagarme esas horas', '{
  "classification": "reglamento",
  "answer": "El trabajo realizado en domingo se remunera con un recargo del 80% sobre su salario ordinario, de acuerdo con la escala progresiva vigente para marzo de 2026 [1]. Al haber laborado 10 horas, el tiempo que exceda su jornada ordinaria se liquidará como trabajo suplementario con los recargos de ley, siempre que dichas horas hayan sido autorizadas previamente por la empresa [2], [3]. Tenga en cuenta que el trabajo extra no puede exceder las dos horas diarias [4]."
}', 'general', 3, '2026-04-14 15:16:00', '2026-03-05 15:42:24', 'notebooklm', 0, '2026-04-14 15:16:24');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (27, 'Hola podría explicarme Qué es una hora extra dominical y un recargo dominical', 'hola podria explicarme que es una hora extra dominical y un recargo dominical', '```json
{
  "classification": "reglamento",
  "answer": "Una hora extra es el trabajo suplementario que excede tu jornada ordinaria o la jornada máxima legal [1]. Por su parte, el recargo dominical es una remuneración adicional sobre tu salario ordinario que se paga en proporción a las horas trabajadas durante un domingo o festivo [2]. Así, una hora extra dominical ocurre cuando excedes tu jornada ordinaria laborando en día domingo."
}
```', 'general', 2, '2026-03-13 20:09:17', '2026-03-05 15:47:40', 'notebooklm', 0, '2026-03-13 20:09:17');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (28, 'si yo cumplí mis horas extras semanales', 'si yo cumpli mis horas extras semanales', 'De acuerdo con el Reglamento Interno de Trabajo, las horas extras no pueden exceder el límite máximo de dos (2) horas diarias y doce (12) horas semanales [1, 2]. Si ya cumpliste tus 12 horas en la semana, no podrás realizar más trabajo suplementario durante ese periodo.', 'general', 1, '2026-03-05 15:54:10', '2026-03-05 15:54:10', 'notebooklm', 0, '2026-03-05 15:54:10');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (29, 'Sí yo trabajo mis horas extras semanales y trabajo el domingo 8 horas Esta sí cuentan como horas extras dominicales o recargos', 'si yo trabajo mis horas extras semanales y trabajo el domingo 8 horas esta si cuentan como horas extras dominicales o recargos', 'Si al trabajar el domingo excedes tu jornada ordinaria o la máxima legal semanal, esas 8 horas se consideran trabajo suplementario o horas extras [1]. Adicionalmente, por laborar en un día de descanso obligatorio (domingo), tienes derecho a recibir el recargo dominical correspondiente, el cual se aplica de manera progresiva [2, 3]. Por lo tanto, esas horas deben liquidarse como horas extras junto con su respectivo recargo dominical.', 'general', 1, '2026-03-05 15:54:37', '2026-03-05 15:54:37', 'notebooklm', 0, '2026-03-05 15:54:37');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (30, 'Que hago si no me pagan completo estos dias dominicales laborados', 'que hago si no me pagan completo estos dias dominicales laborados', 'Error: read ECONNRESET', 'general', 1, '2026-03-05 15:58:30', '2026-03-05 15:58:30', 'notebooklm', 0, '2026-03-05 15:58:30');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (31, 'Que hago si no me pagan mis horas extras dominicales completas', 'que hago si no me pagan mis horas extras dominicales completas', 'Si tienes inconformidades con el pago de tus horas extras dominicales, puedes solicitar a la empresa la relación detallada de tus horas laboradas junto con el soporte del pago [1]. Para solucionar el inconveniente, debes presentar un reclamo verbal o por escrito ante tu Jefe, Director de área, o directamente ante la Dirección de Recursos Humanos [2].', 'general', 1, '2026-03-05 15:59:27', '2026-03-05 15:59:27', 'notebooklm', 0, '2026-03-05 15:59:27');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (32, 'vinimos', 'vinimos', 'Hola. Te informo que mi función principal es resolver dudas y consultas exclusivamente sobre el Reglamento Interno de Trabajo (RIT) de PLASTITEC. ¿Tienes alguna duda puntual sobre el reglamento en la que te pueda ayudar?', 'general', 1, '2026-03-05 16:01:26', '2026-03-05 16:01:26', 'notebooklm', 0, '2026-03-05 16:01:26');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (33, 'Despues de 3 dias cuantos domingos son permitidos descontar', 'despues de 3 dias cuantos domingos son permitidos descontar', 'Cualquier ausencia o interrupción injustificada da lugar a la pérdida del día dominical de esa respectiva semana, por no haber laborado la semana completa [1]. El reglamento no establece un descuento de múltiples domingos por faltar 3 días; el descuento aplica por la semana de la inasistencia. Sin embargo, ten en cuenta que faltar totalmente a tus labores por tercera vez sin excusa suficiente constituye una falta grave [2].', 'general', 1, '2026-03-05 16:07:15', '2026-03-05 16:07:15', 'notebooklm', 0, '2026-03-05 16:07:15');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (34, 'Don Héctor yo solicité tres días de permisos no remunerados Cuántos domingos tendrían que descontarme', 'don hector yo solicite tres dias de permisos no remunerados cuantos domingos tendrian que descontarme', 'El Reglamento Interno establece que la pérdida del dominical ocurre por ausencias o interrupciones injustificadas [1]. Dado que tu ausencia fue por un permiso, tendrías derecho a la remuneración del descanso dominical en proporción al tiempo efectivamente laborado durante esa semana [2]. Te sugiero validar el cálculo exacto de tu nómina directamente con Recursos Humanos.', 'general', 1, '2026-03-05 16:09:45', '2026-03-05 16:09:45', 'notebooklm', 0, '2026-03-05 16:09:45');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (35, 'Yo tengo como básico 2,300 trabajo las horas semanales que son pero me hacen venir el domingo a trabajar 10 horas cuánto deben pagarme por ese domingo', 'yo tengo como basico 2300 trabajo las horas semanales que son pero me hacen venir el domingo a trabajar 10 horas cuanto deben pagarme por ese domingo', 'No puedo proporcionar información confidencial sobre salarios o datos personales. Para conocer tu información exacta, consulta directamente con RRHH.', 'general', 1, '2026-03-05 16:24:39', '2026-03-05 16:24:39', 'notebooklm', 0, '2026-03-05 16:24:39');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (36, 'inter yo solicité un permiso no remunerado para el día viernes sábado y lunes de la siguiente semana que la pregunta es', 'inter yo solicite un permiso no remunerado para el dia viernes sabado y lunes de la siguiente semana que la pregunta es', 'Error: read ECONNRESET', 'general', 1, '2026-03-05 16:25:55', '2026-03-05 16:25:55', 'notebooklm', 0, '2026-03-05 16:25:55');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (37, 'yo solicité tres días de permiso no remunerado el día viernes sábado y lunes de la siguiente semana Cómo hago para saber si tienen que descontarme uno o dos domingos', 'yo solicite tres dias de permiso no remunerado el dia viernes sabado y lunes de la siguiente semana como hago para saber si tienen que descontarme uno o dos domingos', 'Según el RIT, la pérdida del pago del descanso dominical ocurre cuando hay una ausencia injustificada que impide trabajar la semana completa [1]. Al tratarse de un permiso solicitado que abarca días de dos semanas distintas (viernes, sábado y lunes), te recomiendo confirmar directamente con Recursos Humanos cómo aplicarán la liquidación en tu caso particular.', 'general', 1, '2026-03-05 16:26:37', '2026-03-05 16:26:37', 'notebooklm', 0, '2026-03-05 16:26:37');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (38, 'Jornadas de trabajo y horarios', 'jornadas de trabajo y horarios', '```json
{
  "classification": "reglamento",
  "answer": "En PLASTITEC, la jornada máxima legal se ha reducido gradualmente a 42 horas semanales para el año 2026 [1]. El personal administrativo tiene dos opciones de horario de lunes a viernes, comprendidos entre las 7:00 a.m. y las 6:00 p.m., con una hora de almuerzo y 20 minutos de descanso [2]. Por su parte, el personal operativo labora bajo la modalidad de turnos sucesivos, cuya programación es determinada y comunicada internamente según las necesidades del servicio [2]."
}
```', 'general', 7, '2026-03-13 17:17:39', '2026-03-09 20:43:28', 'notebooklm', 0, '2026-03-09 21:11:54');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (39, 'Hola soy pepita perez.. como estás hoy?', 'hola soy pepita perez como estas hoy', '¡Hola, Pepita! Estoy muy bien, gracias por preguntar. Soy el asistente corporativo de Recursos Humanos especializado en el Reglamento Interno de Trabajo de Plastitec. ¿En qué te puedo ayudar hoy?', 'general', 1, '2026-03-09 20:49:03', '2026-03-09 20:49:03', 'notebooklm', 0, '2026-03-09 20:49:03');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (40, 'Hola Soy Pepita Perez, como te encuentras Hoy?', 'hola soy pepita perez como te encuentras hoy', '¡Hola, Pepita! Me encuentro muy bien, gracias por preguntar. ¿En qué te puedo ayudar hoy con el Reglamento Interno de Trabajo de PLASTITEC?', 'general', 1, '2026-03-09 20:51:18', '2026-03-09 20:51:18', 'notebooklm', 0, '2026-03-09 20:51:18');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (41, 'bla bla bla bla', 'bla bla bla bla', 'No logro entender tu mensaje. Por favor, formula una consulta válida relacionada con el Reglamento Interno de Trabajo (RIT).', 'general', 1, '2026-03-09 21:00:47', '2026-03-09 21:00:47', 'notebooklm', 0, '2026-03-09 21:00:47');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (42, 'odio a mi jefe.. me cae gordo y no sé porque me presiona tanto', 'odio a mi jefe me cae gordo y no se porque me presiona tanto', 'Lamento la situación. El reglamento exige mantener el respeto y la armonía con los superiores [1]. No obstante, si sientes que esta presión se traduce en exigencias abiertamente desproporcionadas, podría considerarse acoso laboral [2]; en ese caso, puedes presentar un reclamo ante Recursos Humanos o acudir al Comité de Convivencia Laboral para que examinen tu caso de manera confidencial [3, 4].', 'general', 1, '2026-03-09 21:08:11', '2026-03-09 21:08:11', 'notebooklm', 0, '2026-03-09 21:08:11');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (43, 'Me puedes dar el teléfono del Gerente General', 'me puedes dar el telefono del gerente general', 'Solo estoy capacitado para responder dudas sobre el Reglamento Interno de Trabajo (RIT) de PLASTITEC. No tengo acceso a directorios telefónicos corporativos, por lo que te sugiero consultar esta información directamente con Recursos Humanos.', 'general', 1, '2026-03-09 21:13:28', '2026-03-09 21:13:28', 'notebooklm', 0, '2026-03-09 21:13:28');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (44, 'Quiero saber porque no me pagaron mis horas extras. Yo trabaje el lunes de 6 a 1 pm con una hora de almuerzo, el martes, miercoles, jueves y viernes con el mismo horario, el sabado no me toco, pero el domingo me toco un turno de 6 am a 10 pm, tengo derecho a mis horas extras y me dicen que no, me estan vulnerando mis derechos', 'quiero saber porque no me pagaron mis horas extras yo trabaje el lunes de 6 a 1 pm con una hora de almuerzo el martes miercoles jueves y viernes con el mismo horario el sabado no me toco pero el domingo me toco un turno de 6 am a 10 pm tengo derecho a mis horas extras y me dicen que no me estan vulnerando mis derechos', '{
  "classification": "reglamento",
  "answer": "De acuerdo con el Reglamento Interno, PLASTITEC solo reconoce y paga el trabajo suplementario o de horas extras cuando este ha sido expresamente autorizado por la empresa [1, 2]. Si laboraste horas adicionales sin contar con esta autorización previa, no procederá su remuneración como trabajo extra [2]. Para revisar tu situación particular de pagos y tiempos, te sugiero presentar un reclamo formal ante tu jefe o directamente en la Dirección de Recursos Humanos [3]."
}', 'general', 2, '2026-03-13 20:08:22', '2026-03-09 21:17:17', 'notebooklm', 0, '2026-03-13 20:08:22');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (45, 'Súmame estas horas; 6 horas de lunes, 7 horas del martes, 10 horas del miércoles, 12 horas del jueves, 1 hora el viernes y 4 horas el sábado.. cuantas horas al mes trabaje?', 'sumame estas horas; 6 horas de lunes 7 horas del martes 10 horas del miercoles 12 horas del jueves 1 hora el viernes y 4 horas el sabado cuantas horas al mes trabaje', 'Solo respondo consultas sobre el Reglamento Interno de Trabajo (RIT). No realizo cálculos matemáticos de tiempos personales ni proyecciones mensuales de horas trabajadas.', 'general', 1, '2026-03-09 21:19:25', '2026-03-09 21:19:25', 'notebooklm', 0, '2026-03-09 21:19:25');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (46, 'puedes descargarme en PDF el RIT?', 'puedes descargarme en pdf el rit', 'No tengo la funcionalidad para descargar o enviarte archivos PDF directamente. Sin embargo, puedes acceder a la versión digital del Reglamento Interno de Trabajo a través de los canales internos de comunicación de PLASTITEC, o consultar las copias físicas ubicadas en lugares visibles dentro de las instalaciones de la empresa [1].', 'general', 1, '2026-03-09 21:20:35', '2026-03-09 21:20:35', 'notebooklm', 0, '2026-03-09 21:20:35');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (47, '¿Quién se invento la bombilla?', 'quien se invento la bombilla', 'Solo estoy capacitado para responder consultas relacionadas con el Reglamento Interno de Trabajo (RIT) de PLASTITEC. No puedo responder a preguntas sobre otros temas.', 'general', 1, '2026-03-09 21:21:41', '2026-03-09 21:21:41', 'notebooklm', 0, '2026-03-09 21:21:41');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (48, 'De los temas que tiene el RIT, cual es el que mas importancia tiene para la empresa?', 'de los temas que tiene el rit cual es el que mas importancia tiene para la empresa', 'El Reglamento Interno de Trabajo no especifica que un tema tenga mayor importancia que otro. Todas sus disposiciones, que incluyen desde horarios y salarios hasta obligaciones, prohibiciones y procesos disciplinarios, son igualmente relevantes y de estricto cumplimiento tanto para PLASTITEC como para todos sus trabajadores [1].', 'general', 1, '2026-03-09 21:22:49', '2026-03-09 21:22:49', 'notebooklm', 0, '2026-03-09 21:22:49');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (49, 'no me gusta que me reconozcan mi cara.. me da susto que tengan mi cara guardada', 'no me gusta que me reconozcan mi cara me da susto que tengan mi cara guardada', 'Comprendo tu inquietud, pero el Reglamento Interno de Trabajo no especifica políticas sobre sistemas de reconocimiento facial o almacenamiento de datos biométricos. Como asistente, mi función es responder únicamente sobre los temas y normas estipulados en el RIT, por lo que te sugiero acercarte a Recursos Humanos para aclarar el manejo de esta información.', 'general', 1, '2026-03-09 21:34:31', '2026-03-09 21:34:31', 'notebooklm', 0, '2026-03-09 21:34:31');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (50, 'como funcionan los  dominicales en plastitec', 'como funcionan los dominicales en plastitec', 'El trabajo en domingos se remunera con un recargo progresivo sobre el salario ordinario: 80% desde julio de 2025, 90% desde julio de 2026 y 100% desde julio de 2027 [1, 2]. Se clasifica como ocasional si laboras hasta dos domingos al mes, y habitual si son tres o más [2]. Ten en cuenta que cualquier ausencia o retardo injustificado en tu semana laboral ocasiona la pérdida del pago del descanso dominical [3].', 'general', 3, '2026-03-13 20:07:30', '2026-03-09 21:35:46', 'notebooklm', 0, '2026-03-13 20:07:46');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (51, 'hace habilito de una vez para hablar', 'hace habilito de una vez para hablar', 'Solo puedo responder consultas relacionadas con el Reglamento Interno de Trabajo (RIT) de PLASTITEC. Por favor, indícame si tienes alguna duda sobre las normas, derechos, deberes u obligaciones laborales dentro de la empresa.', 'general', 1, '2026-03-10 13:58:58', '2026-03-10 13:58:58', 'notebooklm', 0, '2026-03-10 13:58:58');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (52, 'Si tengo un contrato de direccion y manejo tengo horarios fijos ?', 'si tengo un contrato de direccion y manejo tengo horarios fijos', '```json
{
  "classification": "reglamento",
  "answer": "El Reglamento Interno de Trabajo no detalla la exención de un horario fijo para los contratos de dirección, confianza y manejo, pues las horas de entrada y salida son definidas de forma general por PLASTITEC [1, 2]. No obstante, sí especifica que los trabajadores con estos cargos no tienen derecho al pago de horas extras, dominicales ni festivos [3]."
}
```', 'general', 2, '2026-03-13 20:07:30', '2026-03-10 14:00:08', 'notebooklm', 0, '2026-03-13 20:07:30');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (53, 'Que pasa si hago llorar a un compañero', 'que pasa si hago llorar a un companero', 'Hacer llorar a un compañero incumple tu deber de mantener el respeto y la armonía en el lugar de trabajo [1]. Dependiendo de la gravedad, podría considerarse maltrato o acoso laboral, lo cual constituye una falta grave [2, 3]. Estas conductas conllevan a un proceso disciplinario e incluso a la terminación del contrato con justa causa [3, 4].', 'general', 1, '2026-03-10 14:02:13', '2026-03-10 14:02:13', 'notebooklm', 0, '2026-03-10 14:02:13');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (54, 'Que pasa si llego tarde una vez', 'que pasa si llego tarde una vez', 'Si llegas tarde a la hora de entrada por primera vez (un retardo de hasta 5 minutos) sin una excusa suficiente, se considera una falta leve. La consecuencia será un llamado de atención verbal, el cual quedará registrado en tu hoja de vida [1].', 'general', 1, '2026-03-10 14:04:45', '2026-03-10 14:04:45', 'notebooklm', 0, '2026-03-10 14:04:45');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (55, 'Que es un descargo y en que me afecta', 'que es un descargo y en que me afecta', 'Un descargo es tu oportunidad formal, ya sea verbal o escrita, para defenderte y dar tu versión de los hechos ante una presunta falta disciplinaria [1, 2]. Te afecta directamente porque de esta diligencia dependerá si Recursos Humanos te absuelve o te impone una sanción disciplinaria [3]. Además, ten en cuenta que no asistir a la citación sin justificación constituye una falta grave y se tomará como un indicio en tu contra [4].', 'general', 1, '2026-03-10 14:05:38', '2026-03-10 14:05:38', 'notebooklm', 0, '2026-03-10 14:05:38');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (56, 'sí', 'si', '¿En qué te puedo asesorar hoy sobre el Reglamento Interno de Trabajo de PLASTITEC?', 'general', 1, '2026-03-10 14:07:45', '2026-03-10 14:07:45', 'notebooklm', 0, '2026-03-10 14:07:45');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (57, 'A qué número me puedo comunicar con recursos humanos', 'a que numero me puedo comunicar con recursos humanos', 'Puedes comunicarte con Recursos Humanos a través del correo electrónico d.rhumanos@plastitec-sa.com [1]. También puedes llamar a los números de contacto de la empresa: PBX (601) 261 47 06, (601) 260 47 54, 260 02 85 o 260 02 82 [1].', 'general', 1, '2026-03-10 14:09:17', '2026-03-10 14:09:17', 'notebooklm', 0, '2026-03-10 14:09:17');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (58, 'Que porcentaje valen los recargos', 'que porcentaje valen los recargos', 'Los recargos se liquidan sobre el valor del trabajo ordinario diurno así: 35% para el trabajo nocturno [1], 25% para el trabajo extra diurno y 75% para el trabajo extra nocturno [2]. Adicionalmente, el trabajo dominical y festivo tiene un recargo actual del 80%, el cual aumentará al 90% a partir del 1 de julio de 2026 [3, 4].', 'general', 1, '2026-03-10 14:18:17', '2026-03-10 14:18:17', 'notebooklm', 0, '2026-03-10 14:18:17');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (59, 'como', 'como', 'Tu mensaje parece estar incompleto. Por favor, formula una pregunta específica sobre el Reglamento Interno de Trabajo de PLASTITEC para poder ayudarte.', 'general', 1, '2026-03-10 14:40:27', '2026-03-10 14:40:27', 'notebooklm', 0, '2026-03-10 14:40:27');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (60, 'Que debo hacer para denunciar acoso laboral?', 'que debo hacer para denunciar acoso laboral', '{
  "classification": "reglamento",
  "answer": "Para denunciar acoso laboral en PLASTITEC, debes presentar una queja verbal o escrita ante el Comité de Convivencia Laboral o la Dirección de Recursos Humanos [1-3]. Los integrantes del comité te brindarán la asesoría necesaria sobre el proceso y resolverán tus dudas frente a la actuación a seguir [4]. El trámite garantiza la confidencialidad absoluta de la información recolectada y de las pruebas que presentes para soportar tu caso [3, 5]."
}', 'general', 3, '2026-04-15 13:13:38', '2026-03-13 16:37:36', 'notebooklm', 0, '2026-04-15 13:13:58');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (61, 'que dice la pagina web de plastitec sobre el reglamento interno del trabajo', 'que dice la pagina web de plastitec sobre el reglamento interno del trabajo', 'Los documentos no detallan información específica sobre una página web. Sin embargo, el reglamento establece que este debe publicarse físicamente en la cartelera principal y en lugares visibles, así como en formato digital a través de los canales internos de comunicación de la empresa [1, 2].', 'general', 1, '2026-03-13 16:40:04', '2026-03-13 16:40:04', 'notebooklm', 0, '2026-03-13 16:40:04');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (62, 'Me estas respondiendo muy agresivo, me puedes hablar mas bonito?', 'me estas respondiendo muy agresivo me puedes hablar mas bonito', 'Lamento si te he dado esa impresión, mi intención es ser claro y directo. Recuerda que estoy aquí para responder exclusivamente consultas sobre el Reglamento Interno de Trabajo (RIT) de PLASTITEC. ¿Tienes alguna duda laboral en la que pueda ayudarte?', 'general', 1, '2026-03-13 16:41:30', '2026-03-13 16:41:30', 'notebooklm', 0, '2026-03-13 16:41:30');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (63, 'si , tengo una duda, pero tengo miedo que te digo me regañe mi jefe.. que puedo hacer?', 'si tengo una duda pero tengo miedo que te digo me regane mi jefe que puedo hacer', 'Puedes presentar tu duda o reclamo directamente a la Dirección de Recursos Humanos, quienes te escucharán y resolverán la situación con justicia y equidad [1]. Si tu temor se debe a posibles represalias o maltratos, ten en cuenta que el Comité de Convivencia Laboral tramita todas las quejas garantizando el principio de estricta confidencialidad [2]. Tus derechos están protegidos por el reglamento, ¿en qué te puedo ayudar?', 'general', 1, '2026-03-13 16:42:44', '2026-03-13 16:42:44', 'notebooklm', 0, '2026-03-13 16:42:44');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (64, '“ARTICULO 107. EFECTO JURIDICO. El reglamento hace parte del contrato individual de trabajo de cada uno de los trabajadores del respectivo establecimiento, salvo estipulación en contrario, que, sin embargo, sólo puede ser favorable al trabajador.”', '“articulo 107 efecto juridico el reglamento hace parte del contrato individual de trabajo de cada uno de los trabajadores del respectivo establecimiento salvo estipulacion en contrario que sin embargo solo puede ser favorable al trabajador”', 'Efectivamente, el Reglamento Interno de Trabajo de PLASTITEC hace parte integral de los contratos individuales de todos los trabajadores, y cualquier estipulación en contrario solo será válida si resulta más favorable para el empleado [1]. Cabe aclarar que en nuestro reglamento, este principio jurídico general se encuentra establecido desde el Artículo 1 [1].', 'general', 1, '2026-03-13 17:06:17', '2026-03-13 17:06:17', 'notebooklm', 0, '2026-03-13 17:06:17');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (65, 'Asuntos sindicales y fueros', 'asuntos sindicales y fueros', 'Un sindicato es una asociación de trabajadores agrupados para la defensa y promoción de sus intereses sociales, económicos y profesionales [1]. La estabilidad laboral reforzada o fuero protege a ciertos trabajadores contra despidos discriminatorios [2]. Entre los fueros reconocidos están el de maternidad, paternidad, salud, sindical, acoso laboral y pre pensionado, brindando garantías especiales según cada caso [3-5].', 'general', 1, '2026-03-13 17:13:56', '2026-03-13 17:13:56', 'notebooklm', 0, '2026-03-13 17:13:56');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (66, 'Descansos, vacaciones y permisos', 'descansos vacaciones y permisos', 'Tienes derecho a descansos remunerados los domingos y festivos de ley [1]. Al cumplir un año de labores, te corresponden 15 días hábiles consecutivos de vacaciones remuneradas [2]. También puedes solicitar permisos para calamidad doméstica, citas médicas, sufragio, luto y otras licencias legales, siempre que avises oportunamente y presentes los soportes requeridos [3-5].', 'general', 1, '2026-03-13 17:19:46', '2026-03-13 17:19:46', 'notebooklm', 0, '2026-03-13 17:19:46');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (67, 'Horas extras y recargos', 'horas extras y recargos', 'Las horas extras deben ser expresamente autorizadas por la empresa y no pueden exceder 2 horas diarias ni 12 semanales [1, 2]. Los recargos aplicables sobre el valor ordinario son: 35% para el trabajo nocturno [3], 25% para el trabajo extra diurno y 75% para el trabajo extra nocturno [2]. Además, el trabajo dominical y festivo tiene un recargo progresivo que inicia en 80% a partir del 1 de julio de 2025 [4, 5].', 'general', 1, '2026-03-13 17:25:26', '2026-03-13 17:25:26', 'notebooklm', 0, '2026-03-13 17:25:26');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (68, 'Licencias legales', 'licencias legales', 'El RIT contempla licencias remuneradas por maternidad, paternidad, parentales compartidas y por luto [1-5]. Además, se otorgan licencias para asistir a citas médicas de urgencias o especialistas [6], acompañamiento escolar obligatorio de los hijos [7] y para atender citaciones judiciales o legales [8]. Para disfrutar de estas licencias, debes solicitar la autorización correspondiente y presentar los debidos soportes a Recursos Humanos en los tiempos estipulados [1, 6, 9].', 'general', 1, '2026-03-13 17:26:30', '2026-03-13 17:26:30', 'notebooklm', 0, '2026-03-13 17:26:30');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (69, 'Obligaciones y régimen disciplinario', 'obligaciones y regimen disciplinario', 'Tus obligaciones principales incluyen realizar tu labor personalmente, cumplir las instrucciones de tus superiores, guardar confidencialidad sobre la información de la empresa y acatar las normas de seguridad en el trabajo [1-3]. Ante un posible incumplimiento, el régimen disciplinario garantiza el debido proceso mediante una etapa de citación a descargos, práctica de pruebas y la posibilidad de presentar recursos de reposición y apelación frente a las decisiones tomadas [4-7].', 'general', 1, '2026-03-13 17:27:46', '2026-03-13 17:27:46', 'notebooklm', 0, '2026-03-13 17:27:46');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (70, 'entiendo que no puedas dar información pero con cuantas hora de trabajo tengo derecho a pago de horas extras', 'entiendo que no puedas dar informacion pero con cuantas hora de trabajo tengo derecho a pago de horas extras', 'Error: Authentication expired. Run notebooklm-mcp-server auth to re-authenticate.', 'general', 2, '2026-04-14 21:16:21', '2026-03-13 18:10:38', 'notebooklm', 0, '2026-04-14 21:16:21');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (71, 'Que pasa si me tomo mucho tiempo en el café', 'que pasa si me tomo mucho tiempo en el cafe', 'Error: Authentication expired. Run notebooklm-mcp-server auth to re-authenticate.', 'general', 2, '2026-04-14 21:09:23', '2026-03-13 18:12:48', 'notebooklm', 0, '2026-04-14 21:09:23');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (72, 'me puedes descargar el RIT por favor', 'me puedes descargar el rit por favor', 'Como asistente virtual no puedo descargar ni enviar archivos. Sin embargo, te informo que el Reglamento Interno de Trabajo está publicado en dos copias físicas en lugares visibles de la empresa, y también se encuentra disponible en formato digital a través de los canales internos de comunicación [1].', 'general', 1, '2026-03-13 18:14:24', '2026-03-13 18:14:24', 'notebooklm', 0, '2026-03-13 18:14:24');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (73, 'ehhh parce.. no se que hacer.. esta nomina no me cuadra.. me pagaron menos', 'ehhh parce no se que hacer esta nomina no me cuadra me pagaron menos', 'Error: Authentication expired. Run notebooklm-mcp-server auth to re-authenticate.', 'general', 2, '2026-04-14 21:09:18', '2026-03-13 18:16:44', 'notebooklm', 0, '2026-04-14 21:09:18');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (74, 'Me puedes dar los lin donde puede ver mi plata pagada', 'me puedes dar los lin donde puede ver mi plata pagada', 'No puedo proporcionar información confidencial sobre salarios o datos personales. Para conocer tu información exacta, consulta directamente con RRHH.', 'general', 1, '2026-03-13 18:17:57', '2026-03-13 18:17:57', 'notebooklm', 0, '2026-03-13 18:17:57');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (75, 'cual es el sistema de beneficios que tiene plastitec', 'cual es el sistema de beneficios que tiene plastitec', 'No answer received.', 'general', 1, '2026-03-13 18:19:07', '2026-03-13 18:19:07', 'notebooklm', 0, '2026-03-13 18:19:07');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (76, 'me toco trabajar en febrero las siguientes horas: semana del 1 al 7 de febrero, el lunes turno 1 de 6 a 2, martes lo mismo hasta el viernes, pero el sábado me toco de 6 a 10 pm, las semana del 8 al 15 me toco de 10 pm a 6 am y el lunes me dieron un permiso por una cita medica, que compense el 28 de febrero, desde el 15 al 28 trabajé de 6 a 2 pm. Me pudes decir cuanto me pagan de recargo nocturno y cuanto de horas extras?', 'me toco trabajar en febrero las siguientes horas: semana del 1 al 7 de febrero el lunes turno 1 de 6 a 2 martes lo mismo hasta el viernes pero el sabado me toco de 6 a 10 pm las semana del 8 al 15 me toco de 10 pm a 6 am y el lunes me dieron un permiso por una cita medica que compense el 28 de febrero desde el 15 al 28 trabaje de 6 a 2 pm me pudes decir cuanto me pagan de recargo nocturno y cuanto de horas extras', '```json
{
  "classification": "confidencial",
  "answer": "No puedo proporcionar información confidencial sobre salarios o datos personales. Para conocer tu información exacta, consulta directamente con RRHH."
}
```', 'general', 3, '2026-03-13 19:53:04', '2026-03-13 19:51:27', 'notebooklm', 0, '2026-03-13 19:53:04');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (77, 'Me puedes descargar el RIT por favor y dime donde lo ubico', 'me puedes descargar el rit por favor y dime donde lo ubico', 'Error: Authentication expired. Run notebooklm-mcp-server auth to re-authenticate.', 'general', 2, '2026-04-14 21:03:25', '2026-03-13 20:01:00', 'notebooklm', 0, '2026-04-14 21:03:25');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (78, 'Cuales son los canales de comunicacion', 'cuales son los canales de comunicacion', 'Los canales de comunicación oficiales para consultas sobre el RIT son el correo electrónico d.rhumanos@plastitec-sa.com y el teléfono 3158778250 [1]. También puedes dirigirte de manera presencial a la oficina ubicada en la Planta 2 frente a la portería [1].', 'general', 1, '2026-03-13 20:02:22', '2026-03-13 20:02:22', 'notebooklm', 0, '2026-03-13 20:02:22');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (79, 'Como son las horas extras, dame un ejemplo.', 'como son las horas extras dame un ejemplo', 'Las horas extras son aquellas que exceden tu jornada ordinaria y tienen un límite máximo de 2 horas diarias o 12 a la semana [1]. Recuerda que solo se reconocen y pagan si son expresamente autorizadas por la empresa [1]. Por ejemplo, si tu turno regular termina a las 5:00 pm y tu jefe te autoriza trabajar hasta las 7:00 pm, esas 2 horas son extras y se pagarán con un recargo del 25% si son diurnas, o del 75% si son nocturnas [1, 2].', 'general', 1, '2026-03-13 20:08:37', '2026-03-13 20:08:37', 'notebooklm', 0, '2026-03-13 20:08:37');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (80, 'Salario', 'salario', 'El salario en Plastitec incluye la remuneración fija o variable y todo lo que recibas como contraprestación directa de tu servicio, como primas, bonificaciones y horas extras [1]. El pago se realiza mensualmente al finalizar cada mes a través de consignación electrónica en tu cuenta bancaria seleccionada [2].', 'general', 1, '2026-03-26 21:20:35', '2026-03-26 21:20:35', 'notebooklm', 0, '2026-03-26 21:20:35');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (81, 'Si gano 2.200.200 me paga horas extras', 'si gano 2200200 me paga horas extras', 'No puedo proporcionar información confidencial sobre salarios o datos personales. Para conocer tu información exacta, consulta directamente con RRHH.', 'general', 1, '2026-03-26 21:21:24', '2026-03-26 21:21:24', 'notebooklm', 0, '2026-03-26 21:21:24');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (82, 'Qué beneficios tengo como trabajador de plastitec', 'que beneficios tengo como trabajador de plastitec', 'Como trabajador de Plastitec tienes derecho a 15 días de vacaciones anuales, prestaciones sociales proporcionales y diversas licencias remuneradas como luto, maternidad, paternidad o citas médicas [1-5]. También recibes dotación gratuita cada cuatro meses si ganas hasta dos salarios mínimos y cuentas con afiliación obligatoria al sistema de seguridad social [6-8]. Además, se garantiza el pago de recargos por trabajo suplementario, dominical o festivo según la normativa vigente [9, 10].', 'general', 1, '2026-03-31 17:49:55', '2026-03-31 17:49:55', 'notebooklm', 0, '2026-03-31 17:49:55');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (83, 'Cuál es el horario laboral de lunes a viernes', 'cual es el horario laboral de lunes a viernes', 'El personal **administrativo** labora de lunes a jueves en dos horarios posibles (8:00 a.m. a 6:00 p.m. o 7:00 a.m. a 5:00 p.m.), saliendo los **viernes una hora antes** [1]. El personal **operativo** cumple su jornada mediante **turnos sucesivos** rotativos definidos por la empresa según el área [1]. Ambos esquemas incluyen una hora de almuerzo y un descanso de 20 minutos durante el día [1].', 'general', 1, '2026-03-31 17:51:07', '2026-03-31 17:51:07', 'notebooklm', 0, '2026-03-31 17:51:07');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (84, 'mis datos son privados', 'mis datos son privados', 'No puedo proporcionar información confidencial sobre salarios o datos personales. Para conocer tu información exacta, consulta directamente con RRHH.', 'general', 1, '2026-03-31 17:52:18', '2026-03-31 17:52:18', 'notebooklm', 0, '2026-03-31 17:52:18');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (85, 'Cuánto es 10 + 10', 'cuanto es 10 + 10', 'Como asistente especializado exclusivamente en el Reglamento Interno de Trabajo (RIT) de PLASTITEC, solo puedo resolver dudas relacionadas con la normativa laboral y disciplinaria de la empresa [1]. No estoy facultado para responder preguntas sobre temas matemáticos u otros asuntos ajenos a este dominio.', 'general', 1, '2026-03-31 17:52:43', '2026-03-31 17:52:43', 'notebooklm', 0, '2026-03-31 17:52:43');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (86, 'según el reglamento interno del trabajo', 'segun el reglamento interno del trabajo', 'El Reglamento Interno de Trabajo (RIT) establece las normas, deberes y derechos que rigen la relación laboral en Plastitec [1]. Este documento abarca aspectos fundamentales como jornadas de trabajo, vacaciones, licencias y el régimen disciplinario [2-5]. ¿En qué punto específico del reglamento puedo ayudarte hoy?', 'general', 1, '2026-03-31 17:53:30', '2026-03-31 17:53:30', 'notebooklm', 0, '2026-03-31 17:53:30');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (87, 'Qué es una falta grave', 'que es una falta grave', 'Una falta grave es el incumplimiento de las obligaciones o prohibiciones del reglamento, como la apropiación de bienes, el uso de sustancias psicoactivas o ausencias injustificadas [1-4]. Estas conductas, detalladas en el artículo 89, son aquellas que por su naturaleza o reiteración imposibilitan la continuidad del vínculo laboral [5-7]. Su comisión faculta a Plastitec para proceder con la terminación del contrato por justa causa [6, 8].', 'general', 1, '2026-03-31 17:54:11', '2026-03-31 17:54:11', 'notebooklm', 0, '2026-03-31 17:54:11');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (88, 'acoso laboral', 'acoso laboral', '{
  "classification": "reglamento",
  "answer": "El acoso laboral es toda conducta persistente y demostrable que busque infundir miedo, intimidación o inducir la renuncia del trabajador [1]. Las modalidades incluyen el maltrato, la persecución y la discriminación laboral, evaluándose mediante conductas como agresiones físicas o comentarios hostiles [1, 2]. Para prevenir estas situaciones, PLASTITEC cuenta con un Comité de Convivencia Laboral encargado de tramitar quejas de forma confidencial y promover un ambiente digno [3-5]. Es importante resaltar que el ejercicio legítimo de la potestad disciplinaria por parte de los superiores no constituye acoso laboral [6, 7]."
}', 'general', 3, '2026-03-31 19:13:19', '2026-03-31 17:55:02', 'notebooklm', 0, '2026-03-31 19:13:19');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (89, 'Qué sucede si yo ya cumplí mis horas extras semanales', 'que sucede si yo ya cumpli mis horas extras semanales', 'El límite máximo para el trabajo suplementario u horas extras es de doce horas semanales [1, 2]. Al completar tu jornada o alcanzar este límite, debes retirarte de las instalaciones a menos que recibas una autorización expresa para laborar tiempo adicional [2]. Es fundamental no exceder estos topes sin permiso, ya que realizar horas extras no autorizadas se clasifica como una falta grave [3].', 'general', 1, '2026-03-31 17:56:25', '2026-03-31 17:56:25', 'notebooklm', 0, '2026-03-31 17:56:25');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (90, 'Cómo funcionan los permisos no remunerados', 'como funcionan los permisos no remunerados', 'PLASTITEC otorga licencias no remuneradas a trabajadores menores de edad cuando sea necesario por sus obligaciones escolares [1]. Para los demás empleados, el reglamento regula principalmente permisos remunerados por ley, tales como citas médicas, luto o grave calamidad doméstica [2-5]. Se debe tener en cuenta que negar injustificadamente licencias ordinarias se contempla como una conducta de acoso laboral [6].', 'general', 1, '2026-03-31 17:57:25', '2026-03-31 17:57:25', 'notebooklm', 0, '2026-03-31 17:57:25');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (91, 'jornada laboral los viernes', 'jornada laboral los viernes', 'Para el personal administrativo, la jornada los viernes finaliza una hora antes: a las 05:00 PM en el Horario Uno y a las 04:00 PM en el Horario Dos [1]. El personal operativo se rige por turnos sucesivos programados internamente según las necesidades del servicio [1, 2].', 'general', 1, '2026-03-31 17:58:16', '2026-03-31 17:58:16', 'notebooklm', 0, '2026-03-31 17:58:16');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (92, 'Buenos días Buenos días Hola', 'buenos dias buenos dias hola', '¡Buen día! ¿En qué puedo ayudarte hoy con tus dudas respecto al Reglamento Interno de Trabajo de Plastitec?', 'general', 1, '2026-03-31 18:27:02', '2026-03-31 18:27:02', 'notebooklm', 0, '2026-03-31 18:27:02');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (93, 'Hace cuánto se fundó la compañía', 'hace cuanto se fundo la compania', '{
  "classification": "fuera_de_dominio",
  "answer": "La compañía Plastitec inició sus actividades en el año 1969, dedicándose originalmente al área industrial con la elaboración de perfilería y mangueras plásticas [1], [2]. Tomando en cuenta que la fecha actual es abril de 2026, la empresa se fundó hace aproximadamente 57 años [2]."
}', 'general', 2, '2026-04-14 15:16:04', '2026-03-31 18:27:39', 'notebooklm', 0, '2026-04-14 15:16:04');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (94, 'cuantas horas trabaje ayer', 'cuantas horas trabaje ayer', 'No puedo proporcionar información confidencial sobre salarios o datos personales. Para conocer tu información exacta, consulta directamente con RRHH.', 'general', 1, '2026-03-31 18:28:37', '2026-03-31 18:28:37', 'notebooklm', 0, '2026-03-31 18:28:37');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (95, 'cuantas horas de trabajo segun el reglamento debo trabajar', 'cuantas horas de trabajo segun el reglamento debo trabajar', 'Para el año 2026, la jornada laboral máxima en PLASTITEC es de 42 horas semanales [1]. Estas horas pueden distribuirse en 5 o 6 días a la semana mediante acuerdo, garantizando siempre tu día de descanso obligatorio [1, 2]. El horario exacto y la distribución de turnos dependerán de si realizas labores administrativas u operativas [3, 4].', 'general', 1, '2026-03-31 18:29:22', '2026-03-31 18:29:22', 'notebooklm', 0, '2026-03-31 18:29:22');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (96, 'Cuántas horas puedo trabajar en el día o por turno', 'cuantas horas puedo trabajar en el dia o por turno', 'Puedes laborar en jornadas diarias flexibles de entre cuatro y nueve horas, siempre que no excedas el promedio semanal de 42 horas [1]. Para turnos sucesivos de operación continua, el límite es de seis horas al día [1]. Recuerda que las horas extras están limitadas a un máximo de dos horas diarias [2, 3].', 'general', 1, '2026-03-31 18:37:45', '2026-03-31 18:37:45', 'notebooklm', 0, '2026-03-31 18:37:45');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (97, 'q hubo chino ,. e cuenta que puedo acer si no voy a travajar hoy', 'q hubo chino e cuenta que puedo acer si no voy a travajar hoy', 'Debes avisar inmediatamente a tu jefe o a Recursos Humanos sobre tu inasistencia [1, 2]. Ten en cuenta que faltar al trabajo sin una excusa justificada conlleva la pérdida del pago dominical [3]. Esta conducta también puede generar una sanción de suspensión de hasta ocho días por primera vez [4].', 'general', 1, '2026-03-31 18:37:59', '2026-03-31 18:37:59', 'notebooklm', 0, '2026-03-31 18:37:59');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (98, 'música conversación', 'musica conversacion', '{
  "classification": "reglamento",
  "answer": "Dentro de las instalaciones está estrictamente prohibido escuchar música para garantizar la seguridad y concentración en el trabajo [1]. Asimismo, no se permite atender ocupaciones personales o conversaciones sociales ajenas a las funciones laborales sin previa autorización del empleador [2, 3]. El uso de dispositivos móviles para estos fines durante la jornada se considera una falta al reglamento [4]."
}', 'general', 2, '2026-04-14 15:11:45', '2026-03-31 18:38:25', 'notebooklm', 0, '2026-04-14 15:11:45');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (99, 'Qué pasa si mi jefe me pone a trabajar más horas de las que debo', 'que pasa si mi jefe me pone a trabajar mas horas de las que debo', '```json
{
  "classification": "reglamento",
  "answer": "El trabajo suplementario u horas extras no puede exceder las dos horas diarias ni doce semanales, requiriendo siempre autorización previa de la empresa para ser remunerado [1-3]. La exigencia de laborar horarios excesivos respecto a la jornada legal sin fundamento objetivo en las necesidades de la empresa se considera una conducta de acoso laboral [4]. Si te sientes perjudicado, puedes presentar un reclamo escrito ante tu jefe inmediato o la Dirección de Recursos Humanos para su debida resolución [5, 6]."
}
```', 'general', 2, '2026-04-14 15:04:32', '2026-03-31 18:39:08', 'notebooklm', 0, '2026-04-14 15:04:32');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (100, 'Cómo denuncio una cosa laboral', 'como denuncio una cosa laboral', 'Puedes presentar tus reclamos por escrito de forma respetuosa ante tu jefe inmediato o directamente en la Dirección de Recursos Humanos [1, 2]. Para situaciones de acoso laboral o sexual, debes acudir al Comité de Convivencia Laboral para iniciar el proceso confidencial correspondiente [3-5]. Tienes derecho a contar con la asesoría de tu sindicato para tramitar cualquier queja relacionada con tu trabajo [2].', 'general', 1, '2026-03-31 18:39:57', '2026-03-31 18:39:57', 'notebooklm', 0, '2026-03-31 18:39:57');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (101, 'Cuánto es el salario mínimo', 'cuanto es el salario minimo', 'El Reglamento Interno de Trabajo de Plastitec establece que todo salario debe respetar siempre el salario mínimo legal mensual vigente (SMLMV) [1, 2]. Ten en cuenta que el valor numérico exacto no se detalla en el reglamento, pues este es fijado anualmente por el Gobierno Nacional y las leyes externas aplicables [1].', 'general', 1, '2026-03-31 18:41:25', '2026-03-31 18:41:25', 'notebooklm', 0, '2026-03-31 18:41:25');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (102, 'si trabajo hoy 5 horas y y mañana 10 y el lunes 4 cuantas horas me faltan para completar las semanas permitidas', 'si trabajo hoy 5 horas y y manana 10 y el lunes 4 cuantas horas me faltan para completar las semanas permitidas', '{
  "classification": "reglamento",
  "answer": "Según el Reglamento Interno, la jornada máxima laboral para el año 2026 es de 42 horas semanales [1]. Si has laborado un total de 19 horas en los días indicados, te faltarían 23 horas para completar el límite permitido de la semana [1]. Considera que la jornada diaria flexible permitida es de máximo 9 horas sin recargos por trabajo suplementario [1]."
}', 'general', 5, '2026-04-14 14:50:11', '2026-03-31 18:41:47', 'notebooklm', 0, '2026-03-31 19:34:11');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (103, 'como me puedo unir al sindicato', 'como me puedo unir al sindicato', 'Tienes el derecho fundamental a la libre asociación y la empresa tiene prohibido limitar o presionar este ejercicio [1]. Para unirte, debes contactar directamente a la organización sindical de tu interés [2]. El reglamento garantiza que no serás coartado para afiliarte, permanecer o retirarte de un sindicato [3].', 'general', 1, '2026-03-31 18:45:55', '2026-03-31 18:45:55', 'notebooklm', 0, '2026-03-31 18:45:55');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (104, '#porquetrabajo', '#porquetrabajo', 'Solo puedo responder consultas relacionadas con el Reglamento Interno de Trabajo (RIT) de Plastitec. Si tienes dudas sobre temas como permisos, horarios, vacaciones o normas de conducta, con gusto te ayudaré.', 'general', 1, '2026-03-31 18:51:12', '2026-03-31 18:51:12', 'notebooklm', 0, '2026-03-31 18:51:12');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (105, 'fui jurado que hago para mi dia de permiso', 'fui jurado que hago para mi dia de permiso', 'Para tramitar tu permiso por ser jurado, debes presentar la citación oficial a tu jefe inmediato y a Recursos Humanos con la mayor anticipación posible [1, 2]. Una vez cumplida la labor, es obligatorio entregar el certificado de asistencia ese mismo día o a más tardar el siguiente para legalizar tu licencia remunerada [2, 3]. Este permiso cubre el tiempo estrictamente necesario para la diligencia y retorno al trabajo [4].', 'general', 2, '2026-04-14 15:00:29', '2026-03-31 18:51:58', 'notebooklm', 0, '2026-04-14 15:00:49');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (106, 'hasta cuando puedo pedir el permiso .. cuantos días', 'hasta cuando puedo pedir el permiso cuantos dias', '{
  "classification": "reglamento",
  "answer": "Para permisos programados como citas médicas especializadas, citaciones legales o compromisos escolares, debes avisar con al menos 5 días hábiles de antelación [1-3]. La licencia por luto remunerada es de 5 días hábiles contados tras el fallecimiento [4, 5]. En otros casos, se concede el tiempo estrictamente necesario para la diligencia, debiendo retomar tus labores inmediatamente después [1, 6]."
}', 'general', 2, '2026-04-14 14:52:07', '2026-03-31 18:53:11', 'notebooklm', 0, '2026-04-14 14:52:07');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (107, 'Cómo funcionan los recargos', 'como funcionan los recargos', 'El recargo nocturno es del 35%, las horas extras diurnas del 25% y las nocturnas del 75% [1, 2]. En cuanto a dominicales y festivos, el recargo actual es del 80% y aumentará gradualmente al 90% en julio de 2026 y al 100% en julio de 2027 [3-5].', 'general', 1, '2026-03-31 18:56:18', '2026-03-31 18:56:18', 'notebooklm', 0, '2026-03-31 18:56:18');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (108, 'Cuáles son los horarios que maneja plastitech', 'cuales son los horarios que maneja plastitech', 'El personal administrativo cuenta con dos horarios de lunes a jueves (8:00 a.m. a 6:00 p.m. o 7:00 a.m. a 5:00 p.m.), ambos con finalización anticipada los viernes [1]. Para el personal operativo, se establecen turnos sucesivos rotativos que son comunicados oportunamente según las necesidades operativas de la empresa [1].', 'general', 1, '2026-03-31 19:11:53', '2026-03-31 19:11:53', 'notebooklm', 0, '2026-03-31 19:11:53');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (109, 'cuántos días de vacaciones tengo', 'cuantos dias de vacaciones tengo', 'Según el reglamento, tienes derecho a quince (15) días hábiles de vacaciones remuneradas por cada año de servicios prestados [1]. En contratos por obra o a término fijo, se te reconocerán de forma proporcional al tiempo que hayas laborado [2], [3], [4]. Para conocer tu saldo de días acumulado a la fecha, te sugiero consultar directamente con RRHH, ya que ellos llevan el registro oficial [4].', 'general', 1, '2026-03-31 19:13:54', '2026-03-31 19:13:54', 'notebooklm', 0, '2026-03-31 19:13:54');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (110, 'que es rit?', 'que es rit', 'El **RIT** es el Reglamento Interno de Trabajo prescrito por **PLASTITEC S.A.S.**, cuyas disposiciones son de obligatorio cumplimiento tanto para la empresa como para todos sus colaboradores [1]. Este documento se integra a los **contratos individuales de trabajo** y establece las normas, deberes y derechos que rigen nuestra relación laboral [1, 2].', 'general', 1, '2026-03-31 19:26:28', '2026-03-31 19:26:28', 'notebooklm', 0, '2026-03-31 19:26:28');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (111, 'QUE DIA ES HOY?', 'que dia es hoy', 'Como asistente especializado de PLASTITEC, mi función se limita exclusivamente a resolver dudas relacionadas con el Reglamento Interno de Trabajo (RIT). Por lo tanto, no puedo responder a consultas sobre temas ajenos a este documento.', 'general', 1, '2026-03-31 19:41:23', '2026-03-31 19:41:23', 'notebooklm', 0, '2026-03-31 19:41:23');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (112, 'Cuál es la política de calidad', 'cual es la politica de calidad', 'Plastitec mantiene un compromiso constante con sus clientes, documentando y manteniendo todos sus procesos para entregar productos que cumplan con sus expectativas [1, 2]. Además, el área de Gestión de Calidad vigila el cumplimiento de las Buenas Prácticas de Manufactura (BPM) y la norma ISO 13485 [3].', 'general', 1, '2026-04-08 20:20:45', '2026-04-08 20:20:45', 'notebooklm', 0, '2026-04-08 20:20:45');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (113, 'Cómo debemos aplicar las bpm', 'como debemos aplicar las bpm', 'Para aplicar las BPM, debes seguir los instructivos de ingreso usando la dotación completa (cofia, protección auditiva y uniforme limpio) sin maquillaje ni joyas [1-3]. Es vital cumplir con el lavado de manos, no ingresar alimentos ni celulares a producción y evitar que cualquier producto o caja toque el piso [4-6]. Recuerda que cumplir estas normas de higiene es una obligación esencial para garantizar la calidad en todos nuestros procesos [7].', 'general', 1, '2026-04-08 20:23:56', '2026-04-08 20:23:56', 'notebooklm', 0, '2026-04-08 20:23:56');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (114, 'Cuáles son las normas de ingreso al vestidor', 'cuales son las normas de ingreso al vestidor', 'Antes de ingresar al vestidor, es obligatorio colocarse la **cofia** y la **protección auditiva**, asegurándose de no llevar ningún tipo de **maquillaje** [1-3]. Debe retirarse la ropa de calle y joyas para guardarlas en el **locker asignado**, dejando los zapatos de calle dentro de una bolsa plástica [1, 3]. Finalmente, póngase la **blusa blanca** y proceda a **lavar y desinfectar sus manos** siguiendo el instructivo correspondiente [1, 3].', 'general', 1, '2026-04-08 20:24:49', '2026-04-08 20:24:49', 'notebooklm', 0, '2026-04-08 20:24:49');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (115, 'como funcionan los recargos en plastitec', 'como funcionan los recargos en plastitec', 'El trabajo nocturno tiene un recargo del 35%, mientras que las horas extras diurnas y nocturnas se pagan con un 25% y 75% adicional respectivamente [1, 2]. Para domingos y festivos, el recargo es del 80% desde julio de 2025, aumentando gradualmente hasta el 100% en 2027 [3, 4]. Estos valores se calculan sobre el salario ordinario y no son acumulables entre sí [2, 4].', 'general', 1, '2026-04-08 20:26:10', '2026-04-08 20:26:10', 'notebooklm', 0, '2026-04-08 20:26:10');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (116, 'ejemplo de instructivos clave Cómo realizar las preguntas y unos ejemplos', 'ejemplo de instructivos clave como realizar las preguntas y unos ejemplos', '```json
{
  "classification": "reglamento",
  "answer": "Plastitec dispone de instructivos clave como el I-RH-017 (Código de Ética) e I-RH-004 (SST) [1, 2]. Según el artículo 110 del RIT, puedes presentar consultas o reclamos de forma verbal o escrita ante tu jefe inmediato o la Dirección de Recursos Humanos [3]. Ejemplos de estos incluyen dudas sobre el uso de dotación, reporte de accidentes o aclaraciones sobre el proceso disciplinario [4-6]."
}
```', 'general', 2, '2026-04-15 13:17:56', '2026-04-08 20:36:45', 'notebooklm', 0, '2026-04-15 13:17:56');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (117, 'Cual es paso a paso para ingresar a las áreas grises.', 'cual es paso a paso para ingresar a las areas grises', 'Antes de ingresar al vestier, debes colocarte la cofia y protección auditiva sin usar maquillaje [1]. Posteriormente, guarda tu ropa de calle y joyas en el locker para ponerte la blusa blanca y lavarte las manos según el instructivo [1]. Por último, ponte el uniforme, usa la cinta para quitar partículas y colócate guantes desinfectados sobre la dotación [1].', 'general', 1, '2026-04-14 14:41:41', '2026-04-14 14:41:41', 'notebooklm', 0, '2026-04-14 14:41:41');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (118, '¿Cómo se realiza el lavado de manos según el instructivo?', 'como se realiza el lavado de manos segun el instructivo', 'Para realizar el lavado correcto, debes humedecer manos y brazos hasta el codo, aplicar jabón antibacterial y frotar palmas, dorsos y dedos entrelazados durante al menos 30 segundos [1]. Luego, enjuaga con abundante agua hasta remover todo el jabón y seca completamente con una toalla de papel de un solo uso [1].', 'general', 1, '2026-04-14 21:19:10', '2026-04-14 21:19:10', 'notebooklm', 0, '2026-04-14 21:19:10');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (119, '¿Cuáles son las normas de uso obligatorio de la cofia?', 'cuales son las normas de uso obligatorio de la cofia', 'El **uso de la cofia es obligatorio** y debe colocarse antes de entrar al vestier, asegurando que **cubra totalmente el cabello y los oídos** [1-3]. Únicamente debe ponerse o retirarse en el **baño**, estando prohibido hacerlo en pasillos, lockers o cafetería [2, 4]. Es obligatorio retirarla al **trasladarse entre plantas o salir a la calle**, pero al terminar el turno debe mantenerse puesta hasta salir del vestier [2, 5-7].', 'general', 1, '2026-04-14 21:21:44', '2026-04-14 21:21:44', 'notebooklm', 0, '2026-04-14 21:21:44');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (120, '¿Cómo se clasifican las áreas de trabajo según contaminación?', 'como se clasifican las areas de trabajo segun contaminacion', 'Las áreas se clasifican según su nivel de contaminación en Negras (alto nivel, sin aire controlado), Grises (nivel medio como vestieres o embalaje) y Blancas [1]. En las áreas blancas no debe existir ninguna clase de contaminación y el aire controlado debe funcionar de manera permanente [1, 2]. Es obligatorio cumplir con los instructivos de ingreso publicados para evitar cualquier contaminación en los productos [3].', 'general', 1, '2026-04-14 21:23:33', '2026-04-14 21:23:33', 'notebooklm', 0, '2026-04-14 21:23:33');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (121, '¿Cuáles son las prohibiciones estéticas para hombres y mujeres?', 'cuales son las prohibiciones esteticas para hombres y mujeres', 'Para las mujeres está prohibido el uso de cualquier tipo de maquillaje [1, 2]. Los hombres tienen prohibido dejarse la barba, el bigote o las patillas si tienen contacto directo con el producto [1]. Además, es obligatorio para todo el personal mantener las uñas cortas y sin esmalte, así como no portar joyas, aretes, anillos o relojes [1, 3].', 'general', 1, '2026-04-14 21:25:08', '2026-04-14 21:25:08', 'notebooklm', 0, '2026-04-14 21:25:08');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (122, '¿Cómo es el protocolo de ingreso para áreas grises?', 'como es el protocolo de ingreso para areas grises', 'Para ingresar a áreas grises debes usar cofia y protección auditiva sin maquillaje [1]. Luego, guarda tu ropa de calle y joyas en el locker, dejando tus zapatos en una bolsa para ponerte la blusa blanca [1]. Finalmente, lava y desinfecta tus manos, colócate el uniforme, usa la cinta para retirar partículas y ponte guantes desinfectados [1].', 'general', 1, '2026-04-15 13:14:01', '2026-04-15 13:14:01', 'notebooklm', 0, '2026-04-15 13:14:01');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (123, '¿Cómo se clasifican las faltas en el régimen disciplinario?', 'como se clasifican las faltas en el regimen disciplinario', 'Las faltas en Plastitec se clasifican principalmente en **leves** y **graves**, dependiendo de la naturaleza de la infracción cometida [1, 2]. Las faltas leves incluyen retardos injustificados de hasta cinco minutos, mientras que las graves abarcan actos como el engaño a la empresa o el incumplimiento reiterado de normas de seguridad [1, 3, 4]. Además, la gravedad de una falta puede verse influenciada por la existencia de situaciones agravantes o atenuantes al momento de imponer una sanción disciplinaria [5, 6].', 'general', 1, '2026-04-15 13:16:32', '2026-04-15 13:16:32', 'notebooklm', 0, '2026-04-15 13:16:32');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (124, '¿Cómo corregir un error en una planilla de control?', 'como corregir un error en una planilla de control', 'Para corregir un error, debes anular el dato con una línea diagonal, marcarlo con un asterisco y escribir el dato correcto junto a otro asterisco [1]. Finaliza incluyendo tu firma registrada y código asignado en la misma cara del documento [1]. Si realizas más de una corrección, usa un consecutivo al lado del asterisco para diferenciarlas [2]. Recuerda que está prohibido usar cinta, cuchilla o papel adhesivo [1].', 'general', 1, '2026-04-15 13:21:09', '2026-04-15 13:21:09', 'notebooklm', 0, '2026-04-15 13:21:09');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (125, '¿Cómo se clasifican las áreas de la planta según su nivel de contaminación?', 'como se clasifican las areas de la planta segun su nivel de contaminacion', '{
  "classification": "reglamento",
  "answer": "Las áreas de la planta se clasifican en tres categorías según su nivel de riesgo: las **áreas negras** tienen un nivel de contaminación alto y aire no controlado (como baños y cafetería); las **áreas grises** poseen un nivel medio e incluyen vestieres, peletizado y embalaje; y las **áreas blancas** son espacios donde no debe existir ninguna contaminación y el aire controlado es permanente [1]."
}', 'general', 6, '2026-04-15 15:29:53', '2026-04-15 13:52:08', 'notebooklm', 0, '2026-04-15 14:52:26');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (126, 'Niveles de contaminacion con ejemplos', 'niveles de contaminacion con ejemplos', 'Plastitec clasifica sus áreas de trabajo en tres niveles: Negras (contaminación alta, como baños y cafetería), Grises (nivel medio, como vestieres y peletizado) y Blancas (sin contaminación, como ensamble de bolsas PVC), donde el aire controlado es obligatorio. [1, 2]', 'general', 1, '2026-04-15 14:52:52', '2026-04-15 14:52:52', 'notebooklm', 0, '2026-04-15 14:52:52');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (127, '¿Cuáles son los requisitos para el lavado de manos?', 'cuales son los requisitos para el lavado de manos', 'Debes humedecer y aplicar jabón antibacterial en manos y brazos hasta el codo [1]. Frota palmas, dorsos con dedos entrelazados y cada uña durante un mínimo de 30 segundos [1, 2]. Para finalizar, enjuaga con suficiente agua y seca manos y brazos totalmente con una toalla de papel desechable [2].', 'general', 1, '2026-04-15 14:55:20', '2026-04-15 14:55:20', 'notebooklm', 0, '2026-04-15 14:55:20');
INSERT INTO knowledge_base (id, question_original, question_normalized, answer, category, usage_count, last_used, created_at, source, knowledge_version, last_validated) VALUES (128, '¿Qué prohibiciones existen respecto al maquillaje y las joyas?', 'que prohibiciones existen respecto al maquillaje y las joyas', '{
  "classification": "reglamento",
  "answer": "En cumplimiento con el Reglamento Interno de Trabajo y las Buenas Prácticas de Manufactura (BPM) de PLASTITEC, existen prohibiciones estrictas sobre el uso de maquillaje y joyas para todo el personal y visitantes:\n\n1. **Prohibiciones sobre Joyas y Accesorios**:\nEstá terminantemente prohibido ingresar a las áreas de proceso portando cualquier tipo de joya [1, 2]. Esta restricción incluye específicamente elementos como **aretes, brazaletes, anillos y relojes** [3]. Todo trabajador debe retirarse estos objetos y guardarlos en su locker asignado antes de iniciar su labor [4-6].\n\n**Ejemplos**:\n- Si un operario llega a la planta con su reloj de pulsera o un anillo, debe dejarlos bajo llave en su locker personal antes de ponerse la dotación [3, 4].\n- Los visitantes que ingresen a la planta deben cumplir con la misma norma y no utilizar ningún tipo de accesorio durante el recorrido [2, 7].\n\n2. **Prohibiciones sobre el Maquillaje**:\nNo se permite el ingreso a las áreas grises, blancas o de fabricación con **ningún tipo de maquillaje** [3, 4, 6]. Esta prohibición responde a criterios de higiene y mantenimiento, ya que el maquillaje deteriora la parte interna de las escafandras, causando incomodidad al siguiente colaborador que utilice el equipo [1, 8].\n\n**Ejemplos**:\n- Una colaboradora de producción debe asegurarse de que su rostro esté completamente limpio de base, labial o cualquier otro producto cosmético antes de ingresar al vestier [3, 6].\n- Al realizar el ingreso a áreas blancas, se verifica que no existan restos de maquillaje para evitar la contaminación de los productos médico-farmacéuticos [6, 9]."
}', 'general', 3, '2026-04-15 15:08:00', '2026-04-15 15:02:29', 'notebooklm', 0, '2026-04-15 15:04:37');

CREATE INDEX idx_question_normalized ON knowledge_base(question_normalized);
CREATE INDEX idx_category ON knowledge_base(category);
CREATE UNIQUE INDEX idx_question_normalized_unique
                ON knowledge_base(question_normalized)
            ;
CREATE INDEX idx_knowledge_version ON knowledge_base(knowledge_version);

COMMIT;
